name: Run Install Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  osm_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install ovos dependencies
        run: |
          pip install ovos-skills-manager~=0.0.10
      - name: Install test dependencies
        run: |
          pip install pytest pytest-timeout pytest-cov
      - name: Install skill with osm
        run: |
          pytest test/osm_tests.py
  msm_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install msm
        run: |
          pip install msm~=0.9.0
      - name: Install skill with msm
        run: |
          msm install https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}
